version: '3.8'

services:
  face_recognition_api:
    build: 
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "8000:8000"
    volumes:
      # Monta la carpeta local known_faces en el contenedor
      - ./known_faces:/app/known_faces
      # Monta el archivo local database.json en el contenedor
      - ./db/database.json:/app/db/database.json
    environment:
      # Puedes sobrescribir la URL de N8N aquí si es diferente a la del Dockerfile
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL:-https://n8n.supervis.ar/webhook-test/e641ceb9-838c-4df7-a3e0-c493ec6b69e8}
    restart: always